# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MesaNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MesaNews
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'
  pod 'SwiftLint'

  target 'MesaNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MesaNewsUITests' do
    # Pods for testing
  end

end
